build(dep): pin click version
ImportError: cannot import name '_unicodefun' from 'click' is a known
issue since 8.1.0. Downgrade click to make it work until the issue is
fixed.